"""Transformation Build Agent — generates the silver→gold transformation.

Produces the conform/dedupe plan for the silver layer and the CTE-based SQL
that joins the five conformed tables into gold.customer_360, registering
bronze→silver→gold lineage. In production this agent would emit dbt models or
Delta Live Tables code with contract quality rules compiled to expectations.
"""

from __future__ import annotations

import json

import yaml

from common.models import AgentResult, PipelineContext, ODCS_PATH, print_report, write_artifact

SOURCE_TABLES = [
    "customer_account",
    "party_details",
    "transaction_details",
    "customer_ticket_details",
    "customer_product_details",
]

CUSTOMER_360_SQL = """-- Generated by transformation-agent (mock) — silver → gold.customer_360
-- Grain: one row per resolved party (contract: customer_360.party_id unique)
CREATE OR REPLACE TABLE gold.customer_360 AS
WITH party AS (
    SELECT party_id, full_name, date_of_birth, kyc_status, risk_rating, marketing_consent
    FROM silver.party_details          -- conformed + deduplicated on party_id
),
accounts AS (
    SELECT party_id,
           COUNT_IF(account_status = 'ACTIVE')                 AS active_account_count,
           SUM(CASE WHEN account_status = 'ACTIVE' THEN balance_eur ELSE 0 END) AS total_balance_eur
    FROM silver.customer_account
    GROUP BY party_id
),
txn_90d AS (
    SELECT a.party_id,
           COUNT(t.transaction_id)                             AS txn_count_90d,
           SUM(t.amount_eur)                                   AS txn_amount_90d,
           MODE(t.channel)                                     AS preferred_channel
    FROM silver.transaction_details t
    JOIN silver.customer_account a USING (account_id)
    WHERE t.txn_timestamp >= current_date() - INTERVAL 90 DAYS
    GROUP BY a.party_id
),
tickets AS (
    SELECT party_id,
           COUNT_IF(status IN ('OPEN', 'IN_PROGRESS'))         AS open_ticket_count,
           AVG(CASE WHEN opened_ts >= current_date() - INTERVAL 12 MONTHS
                    THEN csat_score END)                       AS avg_csat_12m
    FROM silver.customer_ticket_details
    GROUP BY party_id
),
holdings AS (
    SELECT party_id,
           COUNT_IF(status = 'ACTIVE')                         AS product_holding_count,
           COLLECT_SET(CASE WHEN status = 'ACTIVE' THEN product_type END) AS product_types_held
    FROM silver.customer_product_details
    GROUP BY party_id
)
SELECT
    p.party_id,
    p.full_name,
    CONCAT(FLOOR(DATEDIFF(YEAR, p.date_of_birth, current_date()) / 10) * 10 + 5 - 10, '-',
           FLOOR(DATEDIFF(YEAR, p.date_of_birth, current_date()) / 10) * 10 + 4) AS age_band,
    p.kyc_status,
    p.risk_rating,
    p.marketing_consent,
    COALESCE(a.active_account_count, 0)   AS active_account_count,
    COALESCE(a.total_balance_eur, 0)      AS total_balance_eur,
    COALESCE(t.txn_count_90d, 0)          AS txn_count_90d,
    COALESCE(t.txn_amount_90d, 0)         AS txn_amount_90d,
    t.preferred_channel,
    COALESCE(k.open_ticket_count, 0)      AS open_ticket_count,
    k.avg_csat_12m,
    COALESCE(h.product_holding_count, 0)  AS product_holding_count,
    h.product_types_held,
    -- mock churn heuristic: low engagement + open complaints + single product
    LEAST(1.0,
          (CASE WHEN COALESCE(t.txn_count_90d, 0) < 5 THEN 0.4 ELSE 0.1 END)
        + (CASE WHEN COALESCE(k.open_ticket_count, 0) > 0 THEN 0.3 ELSE 0.0 END)
        + (CASE WHEN COALESCE(h.product_holding_count, 0) <= 1 THEN 0.2 ELSE 0.0 END)
    )                                     AS churn_risk_score,
    current_timestamp()                   AS profile_refreshed_ts
FROM party p
LEFT JOIN accounts a USING (party_id)
LEFT JOIN txn_90d  t USING (party_id)
LEFT JOIN tickets  k USING (party_id)
LEFT JOIN holdings h USING (party_id);
"""


def run(ctx: PipelineContext) -> AgentResult:
    contract = yaml.safe_load(ODCS_PATH.read_text(encoding="utf-8"))
    gold = next(o for o in contract["schema"] if o["name"] == "customer_360")

    conform_plan = {
        "silver_conformance": [
            {"table": t, "steps": ["schema-validate against contract", "standardise codes/currency to EUR",
                                   "deduplicate on primary key", "mask-nothing (masking applied at serving)"]}
            for t in SOURCE_TABLES
        ],
        "gold_build": {
            "target": gold.get("physicalName"),
            "grain": gold.get("dataGranularityDescription"),
            "joins": [
                "customer_account.party_id = party_details.party_id",
                "transaction_details.account_id = customer_account.account_id",
                "customer_ticket_details.party_id = party_details.party_id",
                "customer_product_details.party_id = party_details.party_id",
            ],
        },
    }

    plan_artifact = write_artifact("pipelines/transformation/transformation_plan.json",
                                   json.dumps(conform_plan, indent=2))
    sql_artifact = write_artifact("pipelines/transformation/customer_360.sql", CUSTOMER_360_SQL)

    for table in SOURCE_TABLES:
        bronze_node, silver_node = f"bronze_{table}", f"silver_{table}"
        ctx.add_node(silver_node, f"silver.{table}", "silver")
        ctx.add_edge(bronze_node, silver_node, "conform")
        ctx.add_edge(silver_node, "gold_customer_360", "join")
    ctx.add_node("gold_customer_360", "gold.customer_360", "gold")

    ctx.audit("transformation-agent", "transformation-generation", "SUCCESS",
              "silver conformance plan + gold customer_360 SQL generated")

    result = AgentResult(
        agent="transformation-agent",
        status="SUCCESS",
        summary="Generated silver conformance plan and gold customer_360 join SQL "
                f"({len(SOURCE_TABLES)} sources → {gold.get('physicalName')})",
        findings=[
            {"title": "Conformance", "detail": f"{len(SOURCE_TABLES)} silver tables validated/deduplicated per contract"},
            {"title": "Gold build", "detail": f"4 join paths into {gold.get('physicalName')}, "
                                              f"{len(gold.get('properties', []))} output columns incl. churn_risk_score"},
        ],
        artifacts=[plan_artifact, sql_artifact],
    )
    print_report(result)
    return ctx.record(result)


if __name__ == "__main__":
    run(PipelineContext())
