"""Transformation Build Agent — generates and *runs* the silver→gold build.

Produces the conform/dedupe plan for the silver layer and the CTE-based SQL
that documents the join into gold.customer_360, then actually executes the
equivalent logic in Python against the bronze data landed by the ingestion
agent: dedupe each source on its primary key (silver), then join/aggregate
into one customer_360 row per party (gold), registering bronze→silver→gold
lineage. In production this agent would emit dbt models or Delta Live Tables
code with contract quality rules compiled to expectations.
"""

from __future__ import annotations

import json
from collections import Counter, defaultdict
from datetime import date, datetime, timedelta

import yaml

from common.models import (
    AgentResult, PipelineContext, ODCS_PATH, OUTPUT_DIR, REFERENCE_DATE,
    print_report, write_artifact, write_json_artifact,
)

SOURCE_TABLES = [
    "customer_account",
    "party_details",
    "transaction_details",
    "customer_ticket_details",
    "customer_product_details",
]

PRIMARY_KEYS = {
    "customer_account": "account_id",
    "party_details": "party_id",
    "transaction_details": "transaction_id",
    "customer_ticket_details": "ticket_id",
    "customer_product_details": "holding_id",
}

CUSTOMER_360_SQL = """-- Generated by transformation-agent (mock) — silver → gold.customer_360
-- Grain: one row per resolved party (contract: customer_360.party_id unique)
-- The Python execution below (_build_gold) implements this same logic against
-- the landed bronze/silver JSON for the demo run.
CREATE OR REPLACE TABLE gold.customer_360 AS
WITH party AS (
    SELECT party_id, full_name, date_of_birth, kyc_status, risk_rating, marketing_consent
    FROM silver.party_details          -- conformed + deduplicated on party_id
),
accounts AS (
    SELECT party_id,
           COUNT_IF(account_status = 'ACTIVE')                 AS active_account_count,
           SUM(CASE WHEN account_status = 'ACTIVE' THEN balance_eur ELSE 0 END) AS total_balance_eur
    FROM silver.customer_account
    GROUP BY party_id
),
txn_90d AS (
    SELECT a.party_id,
           COUNT(t.transaction_id)                             AS txn_count_90d,
           SUM(t.amount_eur)                                   AS txn_amount_90d,
           MODE(t.channel)                                     AS preferred_channel
    FROM silver.transaction_details t
    JOIN silver.customer_account a USING (account_id)
    WHERE t.txn_timestamp >= current_date() - INTERVAL 90 DAYS
    GROUP BY a.party_id
),
tickets AS (
    SELECT party_id,
           COUNT_IF(status IN ('OPEN', 'IN_PROGRESS'))         AS open_ticket_count,
           AVG(CASE WHEN opened_ts >= current_date() - INTERVAL 12 MONTHS
                    THEN csat_score END)                       AS avg_csat_12m
    FROM silver.customer_ticket_details
    GROUP BY party_id
),
holdings AS (
    SELECT party_id,
           COUNT_IF(status = 'ACTIVE')                         AS product_holding_count,
           COLLECT_SET(CASE WHEN status = 'ACTIVE' THEN product_type END) AS product_types_held
    FROM silver.customer_product_details
    GROUP BY party_id
)
SELECT
    p.party_id,
    p.full_name,
    CONCAT(FLOOR(DATEDIFF(YEAR, p.date_of_birth, current_date()) / 10) * 10, '-',
           FLOOR(DATEDIFF(YEAR, p.date_of_birth, current_date()) / 10) * 10 + 9) AS age_band,
    p.kyc_status,
    p.risk_rating,
    p.marketing_consent,
    COALESCE(a.active_account_count, 0)   AS active_account_count,
    COALESCE(a.total_balance_eur, 0)      AS total_balance_eur,
    COALESCE(t.txn_count_90d, 0)          AS txn_count_90d,
    COALESCE(t.txn_amount_90d, 0)         AS txn_amount_90d,
    t.preferred_channel,
    COALESCE(k.open_ticket_count, 0)      AS open_ticket_count,
    k.avg_csat_12m,
    COALESCE(h.product_holding_count, 0)  AS product_holding_count,
    h.product_types_held,
    -- mock churn heuristic: low engagement + open complaints + single product
    LEAST(1.0,
          (CASE WHEN COALESCE(t.txn_count_90d, 0) < 5 THEN 0.4 ELSE 0.1 END)
        + (CASE WHEN COALESCE(k.open_ticket_count, 0) > 0 THEN 0.3 ELSE 0.0 END)
        + (CASE WHEN COALESCE(h.product_holding_count, 0) <= 1 THEN 0.2 ELSE 0.0 END)
    )                                     AS churn_risk_score,
    current_timestamp()                   AS profile_refreshed_ts
FROM party p
LEFT JOIN accounts a USING (party_id)
LEFT JOIN txn_90d  t USING (party_id)
LEFT JOIN tickets  k USING (party_id)
LEFT JOIN holdings h USING (party_id);
"""


def _load_bronze(table: str) -> list[dict] | None:
    path = OUTPUT_DIR / "bronze" / f"{table}.json"
    if not path.exists():
        return None
    with open(path, encoding="utf-8") as fh:
        return json.load(fh)


def _conform(rows: list[dict], primary_key: str) -> list[dict]:
    """Silver conformance: drop duplicate primary keys, first occurrence wins."""
    seen: set = set()
    conformed = []
    for row in rows:
        key = row.get(primary_key)
        if key in seen:
            continue
        seen.add(key)
        conformed.append(row)
    return conformed


def _age_band(dob_iso: str) -> str:
    dob = date.fromisoformat(dob_iso[:10])
    age = REFERENCE_DATE.year - dob.year - ((REFERENCE_DATE.month, REFERENCE_DATE.day) < (dob.month, dob.day))
    decade = (age // 10) * 10
    return f"{decade}-{decade + 9}"


def _build_gold(silver: dict[str, list[dict]]) -> list[dict]:
    """Python-executed equivalent of CUSTOMER_360_SQL against the silver layer."""
    account_party = {a["account_id"]: a["party_id"] for a in silver["customer_account"]}

    active_accounts: dict[str, int] = defaultdict(int)
    balances: dict[str, float] = defaultdict(float)
    for account in silver["customer_account"]:
        if account["account_status"] == "ACTIVE":
            active_accounts[account["party_id"]] += 1
            balances[account["party_id"]] += account["balance"]

    cutoff_90d = REFERENCE_DATE - timedelta(days=90)
    txn_counts: dict[str, int] = defaultdict(int)
    txn_amounts: dict[str, float] = defaultdict(float)
    txn_channels: dict[str, Counter] = defaultdict(Counter)
    for txn in silver["transaction_details"]:
        party_id = account_party.get(txn["account_id"])
        if not party_id or datetime.fromisoformat(txn["txn_timestamp"]).date() < cutoff_90d:
            continue
        txn_counts[party_id] += 1
        txn_amounts[party_id] += txn["amount"]
        txn_channels[party_id][txn["channel"]] += 1

    cutoff_12m = REFERENCE_DATE - timedelta(days=365)
    open_tickets: dict[str, int] = defaultdict(int)
    csat_scores: dict[str, list] = defaultdict(list)
    for ticket in silver["customer_ticket_details"]:
        if ticket["status"] in ("OPEN", "IN_PROGRESS"):
            open_tickets[ticket["party_id"]] += 1
        if ticket.get("csat_score") not in (None, "") and \
                datetime.fromisoformat(ticket["opened_ts"]).date() >= cutoff_12m:
            csat_scores[ticket["party_id"]].append(ticket["csat_score"])

    active_holdings: dict[str, int] = defaultdict(int)
    product_types: dict[str, set] = defaultdict(set)
    for holding in silver["customer_product_details"]:
        if holding["status"] == "ACTIVE":
            active_holdings[holding["party_id"]] += 1
            product_types[holding["party_id"]].add(holding["product_type"])

    gold_rows = []
    for party in silver["party_details"]:
        pid = party["party_id"]
        t_count = txn_counts.get(pid, 0)
        open_count = open_tickets.get(pid, 0)
        holding_count = active_holdings.get(pid, 0)
        channel_counter = txn_channels.get(pid)

        churn = (0.4 if t_count < 5 else 0.1) + (0.3 if open_count > 0 else 0.0) + (0.2 if holding_count <= 1 else 0.0)

        gold_rows.append({
            "party_id": pid,
            "full_name": party["full_name"],
            "age_band": _age_band(party["date_of_birth"]),
            "kyc_status": party["kyc_status"],
            "risk_rating": party["risk_rating"],
            "marketing_consent": party["marketing_consent"],
            "active_account_count": active_accounts.get(pid, 0),
            "total_balance_eur": round(balances.get(pid, 0.0), 2),
            "txn_count_90d": t_count,
            "txn_amount_90d": round(txn_amounts.get(pid, 0.0), 2),
            "preferred_channel": channel_counter.most_common(1)[0][0] if channel_counter else None,
            "open_ticket_count": open_count,
            "avg_csat_12m": round(sum(csat_scores[pid]) / len(csat_scores[pid]), 2) if csat_scores.get(pid) else None,
            "product_holding_count": holding_count,
            "product_types_held": sorted(product_types.get(pid, [])),
            "churn_risk_score": round(min(churn, 1.0), 4),
            "profile_refreshed_ts": f"{REFERENCE_DATE.isoformat()}T07:00:00",
        })
    return gold_rows


def run(ctx: PipelineContext) -> AgentResult:
    contract = yaml.safe_load(ODCS_PATH.read_text(encoding="utf-8"))
    gold_obj = next(o for o in contract["schema"] if o["name"] == "customer_360")

    bronze = {table: _load_bronze(table) for table in SOURCE_TABLES}
    missing = [table for table, rows in bronze.items() if rows is None]
    if missing:
        result = AgentResult(
            "transformation-agent", "FAILURE",
            f"Missing bronze data for {missing} — run ingestion_agent first",
        )
        print_report(result)
        return ctx.record(result)

    silver = {table: _conform(rows, PRIMARY_KEYS[table]) for table, rows in bronze.items()}
    gold_rows = _build_gold(silver)

    conform_plan = {
        "silver_conformance": [
            {"table": t, "bronze_rows": len(bronze[t]), "silver_rows": len(silver[t]),
             "duplicates_dropped": len(bronze[t]) - len(silver[t]),
             "steps": ["schema-validate against contract", "standardise codes/currency to EUR",
                       "deduplicate on primary key", "mask-nothing (masking applied at serving)"]}
            for t in SOURCE_TABLES
        ],
        "gold_build": {
            "target": gold_obj.get("physicalName"),
            "grain": gold_obj.get("dataGranularityDescription"),
            "rows_produced": len(gold_rows),
            "joins": [
                "customer_account.party_id = party_details.party_id",
                "transaction_details.account_id = customer_account.account_id",
                "customer_ticket_details.party_id = party_details.party_id",
                "customer_product_details.party_id = party_details.party_id",
            ],
        },
    }

    artifacts = [write_json_artifact("pipelines/transformation/transformation_plan.json", conform_plan),
                 write_artifact("pipelines/transformation/customer_360.sql", CUSTOMER_360_SQL)]
    for table in SOURCE_TABLES:
        artifacts.append(write_json_artifact(f"silver/{table}.json", silver[table]))
    artifacts.append(write_json_artifact("gold/customer_360.json", gold_rows))

    for table in SOURCE_TABLES:
        bronze_node, silver_node = f"bronze_{table}", f"silver_{table}"
        ctx.add_node(silver_node, f"silver.{table} ({len(silver[table])} rows)", "silver")
        ctx.add_edge(bronze_node, silver_node, "conform")
        ctx.add_edge(silver_node, "gold_customer_360", "join")
    ctx.add_node("gold_customer_360", f"gold.customer_360 ({len(gold_rows)} rows)", "gold")

    ctx.audit("transformation-agent", "transformation-execution", "SUCCESS",
              f"conformed {sum(len(v) for v in silver.values())} silver rows, "
              f"built {len(gold_rows)} gold customer_360 rows")

    result = AgentResult(
        agent="transformation-agent",
        status="SUCCESS",
        summary=f"Conformed {len(SOURCE_TABLES)} silver tables and built {len(gold_rows)} "
                f"gold customer_360 rows ({gold_obj.get('physicalName')})",
        findings=[
            {"title": "Silver conformance",
             "detail": ", ".join(f"{t}: {len(silver[t])} rows" for t in SOURCE_TABLES)},
            {"title": "Gold build", "detail": f"{len(gold_rows)} rows, "
                                              f"{len(gold_obj.get('properties', []))} columns incl. churn_risk_score"},
        ],
        artifacts=artifacts,
    )
    print_report(result)
    return ctx.record(result)


if __name__ == "__main__":
    run(PipelineContext())
